import Service from '@ember/service';
import { tracked } from '@glimmer/tracking';

export default class MoviesService extends Service {
  @tracked moviesList = [
    {
      id: 1,
      name: 'Pursuit of Happyness',
      year: 2006,
      genre: 'Biography, Drama',
      format: '2D',
      languages: ['English','Tamil'],
      isSelected: false,
    },
    {
      id: 2,
      name: 'Robin-B-Hood',
      year: 2000,
      genre: ' Drama, Action, Comedy',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 3,
      name: 'Fight Club',
      year: 1999,
      genre: ' Thriller, Psychological, Drama',
      format: '2D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 4,
      name: 'Shutter Island',
      year: 2010,
      genre: ' Mystery, Psychological, Thriller',
      format: '2D',
      languages: ['English', 'Tamil', 'Hindi'],
      isSelected: false,
    },
    {
      id: 5,
      name: 'Friends',
      year: 1994,
      genre: ' Sitcom, Drama, Love, Comedy',
      format: '3D',
      languages: ['English'],
      isSelected: false,
    },
    {
      id: 6,
      name: 'Charlie',
      year: 2015,
      genre: ' Love, Drama, Adventure',
      format: '3D',
      languages: ['Tamil', 'Malayalam'],
      isSelected: false,
    },
    {
      id: 7,
      name: 'Chronicles of Narnia',
      year: 2005,
      genre: ' Fantasy, Action, Family',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 8,
      name: 'Grown Ups',
      year: 2004,
      genre: ' Comedy, Drama, Family',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 9,
      name: 'Harry Potter and the Goblet of Fire',
      year: 2001,
      genre: ' Fantasy, Mystery',
      format: '3D',
      languages: ['English', 'Tamil', 'Malayalam'],
      isSelected: false,
    },
    {
      id: 10,
      name: 'The Intern',
      year: 2015,
      genre: ' Comedy, Drama',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 11,
      name: 'Inception',
      year: 2010,
      genre: ' Sci-Fi, Action',
      format: 'IMAX',
      languages: ['English'],
      isSelected: false,
    },
    {
      id: 12,
      name: 'Harry Potter and the Deathly Hallows',
      year: 2001,
      genre: ' Fantasy, Mystery',
      format: '3D',
      languages: ['English', 'Tamil', 'Malayalam'],
      isSelected: false,
    },
    {
      id: 13,
      name: 'Interstellar',
      year: 2014,
      genre: ' Sci-Fi, Adventure, Family',
      format: 'IMAX',
      languages: ['English'],
      isSelected: false,
    },
    {
      id: 14,
      name: 'Grown Ups 2',
      year: 2006,
      genre: ' Comedy, Drama, Family',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 15,
      name: 'Harry Potter and the Order of Phoenix',
      year: 2005,
      genre: ' Fantasy, Mystery, Thriller',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 16,
      name: 'Avengers:Endgame',
      year: 2019,
      genre: ' Superheroes, Action, Thriller',
      format: 'IMAX',
      languages: ['English', 'Tamil','Malayalam'],
      isSelected: false,
    },
    {
      id: 17,
      name: 'Harry Potter and the Chamber of Secrets',
      year: 1998,
      genre: ' Fantasy, Mystery, Thriller',
      format: '3D',
      languages: ['English', 'Tamil','Malayalam'],
      isSelected: false,
    },
    {
      id: 18,
      name: 'Harry potter and the Half-Blood Prince',
      year: 2006,
      genre: ' Fantasy, Mystery, Thriller',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 19,
      name: 'Real steel',
      year: 2012,
      genre: ' Action, Thriller, Drama',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
    {
      id: 20,
      name: 'Lord of the Rings: Fellowship of the Ring',
      year: 1998,
      genre: ' Fantasy, Action, Thriller',
      format: '3D',
      languages: ['English', 'Tamil'],
      isSelected: false,
    },
  ];

  addMovie(movie) {
    this.moviesList = [...this.moviesList, movie];
  }
  
}
